# config/__init__.py
# Configuration package

from .settings import (
    DEFAULT_MODEL_DIR,
    DEFAULT_MODEL_PATH,
    BEST_MODEL_PATH,
    FS,
    NPERSEG,
    NOVERLAP,
    WINDOW,
    MODE,
    EXPECTED_FREQ_BINS,
    EXPECTED_TIME_BINS,
    SPEED_OF_SOUND,
    SENSOR_HEIGHT_CM,
    DEFAULT_DISTANCE_THRESHOLD_CM,
    LED7_ON_COMMAND,
    LED7_OFF_COMMAND,
    LED_TIMER_DURATION,
    SIGNALS_PER_SECOND,
    SIGNAL_DELAY,
    REDPITAYA_HOST_IP,
    REDPITAYA_DATA_PORT,
    REDPITAYA_SSH_PORT,
    SIZE_OF_RAW_ADC
)

__all__ = [
    'DEFAULT_MODEL_DIR',
    'DEFAULT_MODEL_PATH',
    'BEST_MODEL_PATH',
    'FS',
    'NPERSEG',
    'NOVERLAP',
    'WINDOW',
    'MODE',
    'EXPECTED_FREQ_BINS',
    'EXPECTED_TIME_BINS',
    'SPEED_OF_SOUND',
    'SENSOR_HEIGHT_CM',
    'DEFAULT_DISTANCE_THRESHOLD_CM',
    'LED7_ON_COMMAND',
    'LED7_OFF_COMMAND',
    'LED_TIMER_DURATION',
    'SIGNALS_PER_SECOND',
    'SIGNAL_DELAY',
    'REDPITAYA_HOST_IP',
    'REDPITAYA_DATA_PORT',
    'REDPITAYA_SSH_PORT',
    'SIZE_OF_RAW_ADC'
]
